<a href="https://colab.research.google.com/github/rahulyad011/intrusion-detection/blob/main/NIDS1_KDD_Data_preprocessing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import pandas as pd
import numpy as np

In [35]:
col_names = ["duration","protocol_type","service","flag","src_bytes",
    "dst_bytes","land","wrong_fragment","urgent","hot","num_failed_logins",
    "logged_in","num_compromised","root_shell","su_attempted","num_root",
    "num_file_creations","num_shells","num_access_files","num_outbound_cmds",
    "is_host_login","is_guest_login","count","srv_count","serror_rate",
    "srv_serror_rate","rerror_rate","srv_rerror_rate","same_srv_rate",
    "diff_srv_rate","srv_diff_host_rate","dst_host_count","dst_host_srv_count",
    "dst_host_same_srv_rate","dst_host_diff_srv_rate","dst_host_same_src_port_rate",
    "dst_host_srv_diff_host_rate","dst_host_serror_rate","dst_host_srv_serror_rate",
    "dst_host_rerror_rate","dst_host_srv_rerror_rate","label","difficulty_level"]

len(col_names)

43

In [36]:
# Load Binary Classification Dataset

dataset = pd.read_csv("/content/drive/MyDrive/Colab_Notebooks/Datasets/KDDTrain+.txt", header=None, names=col_names)
data = dataset.copy()

In [37]:
# remove attribute 'difficulty_level'
data.drop(['difficulty_level'],axis=1,inplace=True)
data.shape

(125973, 42)

In [38]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 125973 entries, 0 to 125972
Data columns (total 42 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   duration                     125973 non-null  int64
 1   protocol_type                125973 non-null  object
 2   service                      125973 non-null  object
 3   flag                         125973 non-null  object
 4   src_bytes                    125973 non-null  int64
 5   dst_bytes                    125973 non-null  int64
 6   land                         125973 non-null  int64
 7   wrong_fragment               125973 non-null  int64
 8   urgent                       125973 non-null  int64
 9   hot                          125973 non-null  int64
 10  num_failed_logins            125973 non-null  int64
 11  logged_in                    125973 non-null  int64
 12  num_compromised              125973 non-null  int64
 13  root_shell                   125973 non-null  int64
 14  su_attempted                 125973 non-null  int64
 15  num_root                     125973 non-null  int64
 16  num_file_creations           125973 non-null  int64
 17  num_shells                   125973 non-null  int64
 18  num_access_files             125973 non-null  int64
 19  num_outbound_cmds            125973 non-null  int64
 20  is_host_login                125973 non-null  int64
 21  is_guest_login               125973 non-null  int64
 22  count                        125973 non-null  int64
 23  srv_count                    125973 non-null  int64
 24  serror_rate                  125973 non-null  float64
 25  srv_serror_rate              125973 non-null  float64
 26  rerror_rate                  125973 non-null  float64
 27  srv_rerror_rate              125973 non-null  float64
 28  same_srv_rate                125973 non-null  float64
 29  diff_srv_rate                125973 non-null  float64
 30  srv_diff_host_rate           125973 non-null  float64
 31  dst_host_count               125973 non-null  int64
 32  dst_host_srv_count           125973 non-null  int64
 33  dst_host_same_srv_rate       125973 non-null  float64
 34  dst_host_diff_srv_rate       125973 non-null  float64
 35  dst_host_same_src_port_rate  125973 non-null  float64
 36  dst_host_srv_diff_host_rate  125973 non-null  float64
 37  dst_host_serror_rate         125973 non-null  float64
 38  dst_host_srv_serror_rate     125973 non-null  float64
 39  dst_host_rerror_rate         125973 non-null  float64
 40  dst_host_srv_rerror_rate     125973 non-null  float64
 41  label                        125973 non-null  object
dtypes: float64(15), int64(23), object(4)
memory usage: 40.4+ MB

In [39]:
data.describe()

,duration,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,num_failed_logins,logged_in,num_compromised,...,dst_host_count,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate
count,125973.00000,1.259730e+05,1.259730e+05,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,...,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000,125973.000000
mean,287.14465,4.556674e+04,1.977911e+04,0.000198,0.022687,0.000111,0.204409,0.001222,0.395736,0.279250,...,182.148945,115.653005,0.521242,0.082951,0.148379,0.032542,0.284452,0.278485,0.118832,0.120240
std,2604.51531,5.870331e+06,4.021269e+06,0.014086,0.253530,0.014366,2.149968,0.045239,0.489010,23.942042,...,99.206213,110.702741,0.448949,0.188922,0.308997,0.112564,0.444784,0.445669,0.306557,0.319459
min,0.00000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.00000,0.000000e+00,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,82.000000,10.000000,0.050000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.00000,4.400000e+01,0.000000e+00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,255.000000,63.000000,0.510000,0.020000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,0.00000,2.760000e+02,5.160000e+02,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,...,255.000000,255.000000,1.000000,0.070000,0.060000,0.020000,1.000000,1.000000,0.000000,0.000000
max,42908.00000,1.379964e+09,1.309937e+09,1.000000,3.000000,3.000000,77.000000,5.000000,1.000000,7479.000000,...,255.000000,255.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [40]:
# missing value checks
data.isnull().sum()

duration                       0
protocol_type                  0
service                        0
flag                           0
src_bytes                      0
dst_bytes                      0
land                           0
wrong_fragment                 0
urgent                         0
hot                            0
num_failed_logins              0
logged_in                      0
num_compromised                0
root_shell                     0
su_attempted                   0
num_root                       0
num_file_creations             0
num_shells                     0
num_access_files               0
num_outbound_cmds              0
is_host_login                  0
is_guest_login                 0
count                          0
srv_count                      0
serror_rate                    0
srv_serror_rate                0
rerror_rate                    0
srv_rerror_rate                0
same_srv_rate                  0
diff_srv_rate                  0
srv_diff_host_rate             0
dst_host_count                 0
dst_host_srv_count             0
dst_host_same_srv_rate         0
dst_host_diff_srv_rate         0
dst_host_same_src_port_rate    0
dst_host_srv_diff_host_rate    0
dst_host_serror_rate           0
dst_host_srv_serror_rate       0
dst_host_rerror_rate           0
dst_host_srv_rerror_rate       0
label                          0
dtype: int64

In [41]:
data.label.value_counts()

normal             67343
neptune            41214
satan               3633
ipsweep             3599
portsweep           2931
smurf               2646
nmap                1493
back                 956
teardrop             892
warezclient          890
pod                  201
guess_passwd          53
buffer_overflow       30
warezmaster           20
land                  18
imap                  11
rootkit               10
loadmodule             9
ftp_write              8
multihop               7
phf                    4
perl                   3
spy                    2
Name: label, dtype: int64

In [42]:
# changing different labels to their respective broad class
# I will convert other abnormal classes to one class

data["binary_label"]=data.label.map(lambda a: "normal" if a == 'normal' else "abnormal")
data.drop('label',axis=1,inplace=True)

In [43]:
# distribution of attack classes
data.binary_label.value_counts()

normal      67343
abnormal    58630
Name: binary_label, dtype: int64

In [44]:
data.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,binary_label
0,0,tcp,ftp_data,SF,491,0,0,0,0,0,...,25,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal
1,0,udp,other,SF,146,0,0,0,0,0,...,1,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal
2,0,tcp,private,S0,0,0,0,0,0,0,...,26,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,abnormal
3,0,tcp,http,SF,232,8153,0,0,0,0,...,255,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal
4,0,tcp,http,SF,199,420,0,0,0,0,...,255,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal

In [45]:
# saving final dataset to disk
data_unprocessed = data.copy()

data_unprocessed.to_csv("/content/drive/MyDrive/Colab_Notebooks/nids_project_data/bin_data_unprocessed.csv")
# import os
# os.getcwd()

Split Data into Train and Test

In [46]:
# from sklearn.model_selection import train_test_split
# y = data['binary_label']
# features = data.columns
# features = features[0:-1]
# features
# X = data[features]
# X_train, y_train, X_test, y_test = train_test_split(X, y, test_size=0.25, random_state=42)
# print(np.shape(X))
# print(np.shape(y))
# print(np.shape(X_train))
# print(np.shape(y_train))
# print(np.shape(X_test))
# print(np.shape(y_test))

**Data Normalization and Encoding**

In [51]:
# numeric feature normalization
from sklearn.preprocessing import MinMaxScaler
from sklearn.preprocessing import StandardScaler

numeric_cols = data.select_dtypes(['number']).columns
flag = 0
scaler = None
if flag:
  # using standard scaler for normalizing
  scaler = StandardScaler()
else:
  # using minmax scaler for normalizing
  # to avoid negative values after scaling
  scaler = MinMaxScaler()

def normalization(df,col):
  for i in col:
    arr = df[i]
    arr = np.array(arr)
    df[i] = scaler.fit_transform(arr.reshape(len(arr),1))
  return df

In [53]:
# calling the normalization() function
data_num = normalization(data.copy(),numeric_cols)
data_num.head()

,duration,protocol_type,service,flag,src_bytes,dst_bytes,land,wrong_fragment,urgent,hot,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,binary_label
0,0.0,tcp,ftp_data,SF,3.558064e-07,0.000000e+00,0.0,0.0,0.0,0.0,...,0.098039,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal
1,0.0,udp,other,SF,1.057999e-07,0.000000e+00,0.0,0.0,0.0,0.0,...,0.003922,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal
2,0.0,tcp,private,S0,0.000000e+00,0.000000e+00,0.0,0.0,0.0,0.0,...,0.101961,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,abnormal
3,0.0,tcp,http,SF,1.681203e-07,6.223962e-06,0.0,0.0,0.0,0.0,...,1.000000,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal
4,0.0,tcp,http,SF,1.442067e-07,3.206260e-07,0.0,0.0,0.0,0.0,...,1.000000,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal

In [54]:
# check for categorical colummns in a pandas dataframe
cat_cols = data.select_dtypes(['object']).columns
print(cat_cols)
cat_cols_without_label = ['protocol_type', 'service', 'flag']
data_categorical = pd.get_dummies(data[cat_cols_without_label],columns=cat_cols_without_label) 
data_categorical.head()

Index(['protocol_type', 'service', 'flag', 'binary_label'], dtype='object')

,protocol_type_icmp,protocol_type_tcp,protocol_type_udp,service_IRC,service_X11,service_Z39_50,service_aol,service_auth,service_bgp,service_courier,...,flag_REJ,flag_RSTO,flag_RSTOS0,flag_RSTR,flag_S0,flag_S1,flag_S2,flag_S3,flag_SF,flag_SH
0,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
1,0,0,1,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
2,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,1,0,0,0,0,0
3,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
4,0,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0

In [55]:
data_processed = data_num.copy()
data_processed = data_processed.drop(cat_cols_without_label, axis = 1)
data_processed = data_categorical.join(data_processed)
data_processed

,protocol_type_icmp,protocol_type_tcp,protocol_type_udp,service_IRC,service_X11,service_Z39_50,service_aol,service_auth,service_bgp,service_courier,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,binary_label
0,0,1,0,0,0,0,0,0,0,0,...,0.098039,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,normal
1,0,0,1,0,0,0,0,0,0,0,...,0.003922,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,normal
2,0,1,0,0,0,0,0,0,0,0,...,0.101961,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,abnormal
3,0,1,0,0,0,0,0,0,0,0,...,1.000000,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,normal
4,0,1,0,0,0,0,0,0,0,0,...,1.000000,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125968,0,1,0,0,0,0,0,0,0,0,...,0.098039,0.10,0.06,0.00,0.00,1.00,1.00,0.00,0.00,abnormal
125969,0,0,1,0,0,0,0,0,0,0,...,0.956863,0.96,0.01,0.01,0.00,0.00,0.00,0.00,0.00,normal
125970,0,1,0,0,0,0,0,0,0,0,...,0.117647,0.12,0.06,0.00,0.00,0.72,0.00,0.01,0.00,normal
125971,0,1,0,0,0,0,0,0,0,0,...,0.031373,0.03,0.05,0.00,0.00,1.00,1.00,0.00,0.00,abnormal
125972,0,1,0,0,0,0,0,0,0,0,...,0.301961,0.30,0.03,0.30,0.00,0.00,0.00,0.00,0.00,normal

In [56]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
data_processed['binary_label'] = le.fit_transform(data_processed['binary_label'])
# data_processed['binary_label'].value_counts()
data_processed.head()

,protocol_type_icmp,protocol_type_tcp,protocol_type_udp,service_IRC,service_X11,service_Z39_50,service_aol,service_auth,service_bgp,service_courier,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,binary_label
0,0,1,0,0,0,0,0,0,0,0,...,0.098039,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,1
1,0,0,1,0,0,0,0,0,0,0,...,0.003922,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,1
2,0,1,0,0,0,0,0,0,0,0,...,0.101961,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,0
3,0,1,0,0,0,0,0,0,0,0,...,1.000000,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,1
4,0,1,0,0,0,0,0,0,0,0,...,1.000000,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1

In [57]:
# saving final dataset to disk
data_processed.to_csv("/content/drive/MyDrive/Colab_Notebooks/nids_project_data/bin_data_processed.csv")
# final dataset for binary classification
data_processed

,protocol_type_icmp,protocol_type_tcp,protocol_type_udp,service_IRC,service_X11,service_Z39_50,service_aol,service_auth,service_bgp,service_courier,...,dst_host_srv_count,dst_host_same_srv_rate,dst_host_diff_srv_rate,dst_host_same_src_port_rate,dst_host_srv_diff_host_rate,dst_host_serror_rate,dst_host_srv_serror_rate,dst_host_rerror_rate,dst_host_srv_rerror_rate,binary_label
0,0,1,0,0,0,0,0,0,0,0,...,0.098039,0.17,0.03,0.17,0.00,0.00,0.00,0.05,0.00,1
1,0,0,1,0,0,0,0,0,0,0,...,0.003922,0.00,0.60,0.88,0.00,0.00,0.00,0.00,0.00,1
2,0,1,0,0,0,0,0,0,0,0,...,0.101961,0.10,0.05,0.00,0.00,1.00,1.00,0.00,0.00,0
3,0,1,0,0,0,0,0,0,0,0,...,1.000000,1.00,0.00,0.03,0.04,0.03,0.01,0.00,0.01,1
4,0,1,0,0,0,0,0,0,0,0,...,1.000000,1.00,0.00,0.00,0.00,0.00,0.00,0.00,0.00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125968,0,1,0,0,0,0,0,0,0,0,...,0.098039,0.10,0.06,0.00,0.00,1.00,1.00,0.00,0.00,0
125969,0,0,1,0,0,0,0,0,0,0,...,0.956863,0.96,0.01,0.01,0.00,0.00,0.00,0.00,0.00,1
125970,0,1,0,0,0,0,0,0,0,0,...,0.117647,0.12,0.06,0.00,0.00,0.72,0.00,0.01,0.00,1
125971,0,1,0,0,0,0,0,0,0,0,...,0.031373,0.03,0.05,0.00,0.00,1.00,1.00,0.00,0.00,0
125972,0,1,0,0,0,0,0,0,0,0,...,0.301961,0.30,0.03,0.30,0.00,0.00,0.00,0.00,0.00,1

In [58]:
# creating a dataframe with only numeric attributes of binary class dataset and encoded label attribute 
numeric_bin = data_processed[numeric_cols]
# numeric_bin
numeric_bin['binary_label'] = data_processed['binary_label']

<ipython-input-58-6d18a77738db>:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  numeric_bin['binary_label'] = data_processed['binary_label']

In [59]:
corr= numeric_bin.corr()
corr_y = abs(corr['binary_label'])
highest_corr = corr_y[corr_y >0.5]
highest_corr.sort_values(ascending=True)

count                       0.576444
srv_serror_rate             0.648289
serror_rate                 0.650652
dst_host_serror_rate        0.651842
dst_host_srv_serror_rate    0.654985
logged_in                   0.690171
dst_host_same_srv_rate      0.693803
dst_host_srv_count          0.722535
same_srv_rate               0.751913
binary_label                1.000000
Name: binary_label, dtype: float64